/**
 * AI Studio Generated Code - Comet Orchestrator
 * Generated: October 23, 2025
 * Source: Google AI Studio (Gemini 2.5 Pro)
 * 
 * This is the original code generated by AI Studio for the Comet agent.
 * We'll integrate key parts into our main application.
 */

import React, { useState, useCallback, FC } from 'react';
import { Agent, LogEntry, LogStatus } from './types';
import { AGENTS } from './constants';
import { analyzeIntent } from './services/geminiService';
import { CheckCircleIcon, XCircleIcon, InfoCircleIcon, CogIcon, RocketIcon } from './components/icons';

const LogItem: FC<{ entry: LogEntry }> = ({ entry }) => {
  const ICONS: Record<LogStatus, React.ReactNode> = {
    info: <InfoCircleIcon className="h-6 w-6 text-blue-400" />,
    loading: <div className="h-5 w-5 border-2 border-t-blue-400 border-gray-600 rounded-full animate-spin"></div>,
    success: <CheckCircleIcon className="h-6 w-6 text-green-400" />,
    error: <XCircleIcon className="h-6 w-6 text-red-400" />,
    pending: <CogIcon className="h-6 w-6 text-yellow-400" />,
  };

  return (
    <div className="flex items-start space-x-4 p-4 bg-gray-800/50 rounded-lg">
      <div className="flex-shrink-0 mt-1">{ICONS[entry.status]}</div>
      <div>
        <h3 className="font-semibold text-gray-200">{entry.title}</h3>
        <p className="text-sm text-gray-400">{entry.details}</p>
      </div>
    </div>
  );
};

const AgentCard: FC<{ agent: Agent, isSelected: boolean }> = ({ agent, isSelected }) => (
    <div className={`p-4 border rounded-lg transition-all duration-300 ${isSelected ? 'border-blue-500 bg-blue-900/30 scale-105' : 'border-gray-700 bg-gray-800'}`}>
        <h3 className="font-bold text-lg text-blue-300">{agent.name}</h3>
        <p className="text-sm text-gray-400 capitalize mb-2">Role: {agent.role}</p>
        <p className="text-xs text-gray-500 break-all">DID: {agent.did}</p>
    </div>
);


const App: FC = () => {
  const [userInput, setUserInput] = useState('Buy headphones for $150');
  const [isLoading, setIsLoading] = useState(false);
  const [logEntries, setLogEntries] = useState<LogEntry[]>([]);
  const [selectedAgentId, setSelectedAgentId] = useState<string | null>(null);

  const addLogEntry = (entry: Omit<LogEntry, 'id'>) => {
    setLogEntries(prev => [...prev, { ...entry, id: prev.length }]);
  };

  const simulateDelay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

  const handleSubmit = useCallback(async (event: React.FormEvent) => {
    event.preventDefault();
    if (!userInput.trim() || isLoading) return;

    setIsLoading(true);
    setLogEntries([]);
    setSelectedAgentId(null);

    try {
      addLogEntry({ title: 'Request Received', details: `User request: "${userInput}"`, status: 'info' });
      await simulateDelay(500);

      addLogEntry({ title: 'Analyzing Intent...', details: 'Contacting Gemini for agent selection.', status: 'loading' });
      const { selectedAgentId: agentId, reason } = await analyzeIntent(userInput, AGENTS);
      const selectedAgent = AGENTS.find(a => a.did === agentId);

      if (!selectedAgent) {
        throw new Error(`Agent with DID ${agentId} not found.`);
      }
      setSelectedAgentId(agentId);
      addLogEntry({ title: 'Agent Selected: ' + selectedAgent.name, details: `Reason: ${reason}`, status: 'success' });
      await simulateDelay(500);

      addLogEntry({ title: 'Verifying Agent Credentials...', details: `Initiating Zero-Knowledge Proof (ZKP) verification for ${selectedAgent.name}.`, status: 'loading' });
      await simulateDelay(1500); // Simulate ZKP
      const isVerified = true; // Simulating success

      if (!isVerified) {
        addLogEntry({ title: 'Verification Failed', details: 'Agent credentials could not be verified. Halting operation.', status: 'error' });
        return;
      }
      addLogEntry({ title: 'Credential Verification Successful', details: 'ZKP proof is valid. Agent is authorized.', status: 'success' });
      await simulateDelay(500);

      const privacyRatio = Math.floor(Math.random() * (95 - 75 + 1) + 75);
      addLogEntry({ title: 'Enhancing Privacy', details: `Generating ${privacyRatio}% spoof transactions to obscure real activity.`, status: 'pending' });
      await simulateDelay(1000);

      addLogEntry({ title: 'Executing Action', details: 'Delegating task to agent with privacy protection enabled.', status: 'success' });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : 'An unknown error occurred.';
      addLogEntry({ title: 'Orchestration Failed', details: errorMessage, status: 'error' });
    } finally {
      setIsLoading(false);
    }
  }, [userInput, isLoading]);

  return (
    <div className="min-h-screen bg-gray-900 text-gray-100 font-sans p-4 sm:p-6 lg:p-8">
      <div className="max-w-7xl mx-auto">
        <header className="text-center mb-10">
          <div className="inline-flex items-center space-x-3 mb-2">
              <RocketIcon className="h-10 w-10 text-blue-400" />
              <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
                Comet
              </h1>
          </div>
          <p className="text-lg text-gray-400">A Local, Privacy-Preserving AI Agent Orchestrator</p>
        </header>

        <main className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Left Column: Input and Agents */}
          <div className="flex flex-col space-y-8">
            <div className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
              <h2 className="text-2xl font-semibold mb-4 text-gray-200">1. User Request</h2>
              <form onSubmit={handleSubmit}>
                <textarea
                  value={userInput}
                  onChange={(e) => setUserInput(e.target.value)}
                  className="w-full h-24 p-3 bg-gray-900 border border-gray-600 rounded-md focus:ring-2 focus:ring-blue-500 focus:outline-none transition-shadow text-gray-200"
                  placeholder="e.g., Check my bank balance"
                />
                <button
                  type="submit"
                  disabled={isLoading}
                  className="mt-4 w-full bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-bold py-3 px-4 rounded-md transition-all duration-300 flex items-center justify-center space-x-2"
                >
                  {isLoading && <div className="h-5 w-5 border-2 border-t-white/50 border-white/80 rounded-full animate-spin"></div>}
                  <span>{isLoading ? 'Orchestrating...' : 'Start Orchestration'}</span>
                </button>
              </form>
            </div>

            <div className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
                <h2 className="text-2xl font-semibold mb-4 text-gray-200">Available Agents</h2>
                <div className="space-y-4">
                    {AGENTS.map(agent => (
                        <AgentCard key={agent.did} agent={agent} isSelected={selectedAgentId === agent.did} />
                    ))}
                </div>
            </div>
          </div>

          {/* Right Column: Orchestration Log */}
          <div className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
            <h2 className="text-2xl font-semibold mb-4 text-gray-200">2. Orchestration Log</h2>
            <div className="space-y-3 h-[600px] overflow-y-auto pr-2">
              {logEntries.length === 0 ? (
                <div className="flex flex-col items-center justify-center h-full text-gray-500">
                  <CogIcon className="h-16 w-16 mb-4"/>
                  <p>Log will appear here once orchestration begins.</p>
                </div>
              ) : (
                logEntries.map(entry => <LogItem key={entry.id} entry={entry} />)
              )}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
};

export default App;
